name: Build and Create RoveComm Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read
  packages: read
  id-token: write

concurrency:
  group: "create-release"
  cancel-in-progress: false

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: /opt/
          submodules: "recursive"

      - name: Fix Dubious Ownership
        run: git config --global --add safe.directory /opt/RoveComm_CPP

      - name: Checkout Tag
        run: |
          cd /opt/RoveComm_CPP/
          git fetch --tags --force
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $tag
          git checkout $tag

      - name: Build and Create Executable
        run: |
          cd /opt/RoveComm_CPP/
          if [ -d "build" ]; then rm -Rf build; fi
          mkdir build
          cd build
          cmake ..
          make
          make package

      - name: Rename Executable
        run: mv /opt/RoveComm_CPP/build/RoveComm_CPP**.sh /opt/RoveComm_CPP/build/RoveComm_CPP_AMD64.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RoveComm-AMD64
          path: /opt/RoveComm_CPP/build/RoveComm_CPP_AMD64.sh

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-upload

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: /opt/
          submodules: "recursive"

      - name: Fix Dubious Ownership
        run: git config --global --add safe.directory /opt/RoveComm_CPP

      - name: Determine Version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Directory
        run: mkdir -p /opt/RoveComm_CPP/artifacts/

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        id: download
        with:
          path: /opt/RoveComm_CPP/artifacts/

      - name: Display Structure
        run: ls
        working-directory: /opt/RoveComm_CPP/artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          name: "${{ steps.version.outputs.version }}"
          files: "/opt/RoveComm_CPP/artifacts/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
