name: Update Manifest Header

on:
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: "manifest-generator"
  cancel-in-progress: true

jobs:
  update-manifest:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/update-manifest') }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo
        uses: actions/checkout@v4

      - name: Generate Manifest
        run: |
          git branch
          cd tools/RoveComm
          python parser.py

      - name: Setup Git
          git config user.name "MissouriMRDT"
          git config user.email "marsrover@mst.edu"

      - name: Commit Manifest
          git add -f ../../src/RoveComm/Manifest.h
          git commit -m "** Automated - Manifest Update **"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
